#vim mongo.yaml
version: '3'
services:
  mongodb:
    restart: always
    network_mode: bridge
    image: mongo:latest
    container_name: graylog-mongo
    volumes:
      - ./data/graylog-mongo:/data/db
      - ./data/log:/var/log/mongodb
      - ./mongodb.key:/data/mongodb.key
    ports:
       - 27017:27017
    environment:
         MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #启动命令，--replSet mongos 以副本集形式启动并将副本集名字命名为 mongos ，
    #        --keyFile /data/mongodb.key 设置keyFile，用于副本集通信     
    command: mongod --replSet mongos --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        #999用户是容器中的mongod用户，通过chown修改文件用户权限
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
################################################################################## /data/
